create changeset using existing tags to help identify changes (#49)
## Summary

- Routine Change

### Details

- When displaying changes, also do it for existing tags so that it is
easier to identify changes

## Reviews Required

**Check who should review this. Remove this line once this has been
done**

- [x] Dev
- [ ] Test
- [ ] Tech Author
- [ ] Product Owner

## Review Checklist

:information_source: This section is to be filled in by the
**reviewer**.

- [ ] I have reviewed the changes in this PR and they fill all or part
of the acceptance criteria of the ticket, and the code is in a mergeable
state.
- [ ] I have reviewed any infrastructure changes listed in the workflow
summary.
- [ ] If there were infrastructure, operational, or build changes, I
have made sure there is sufficient evidence that the changes will work.
- [ ] I have ensured the jira ticket has been updated with the github
pull request link

diff --git a/.github/workflows/cloudformation.yml b/.github/workflows/cloudformation.yml
--- a/.github/workflows/cloudformation.yml
+++ b/.github/workflows/cloudformation.yml
@@ -59,7 +59,7 @@ jobs:
       run: |
         echo PARAMETERS=$(python scripts/parse_parameters.py ${{ inputs.target_environment }} ${{ inputs.stack_name }}) >> $GITHUB_OUTPUT
 
-    - name: Create Change Set
+    - name: Create Change Set with new tags
       shell: bash
       run: |
         ROLE=$(aws cloudformation list-exports --output json | \
@@ -73,8 +73,38 @@ jobs:
         --parameters ${{ steps.parse_parameters.outputs.PARAMETERS }} \
         --tags Key="version",Value="${{ inputs.version }}" \
         --role-arn="$ROLE"
-      
-    - name: Describe Change Set
+
+    - name: Create Change Set with existing tags
+      shell: bash
+      run: |
+        current_deployed_tag=$(aws cloudformation describe-stacks --stack-name  ${{ inputs.stack_name }} --query "Stacks[0].Tags[?Key=='version'].Value" --output text)
+        if [ "${current_deployed_tag}" == "" ]; then
+          echo "Can not find target tag. Using initial tag in repo"
+          export current_deployed_tag="v1.0.4-alpha"
+          fi
+        ROLE=$(aws cloudformation list-exports --output json | \
+        jq -r '.Exports[] | select(.Name == "ci-resources:CloudFormationExecutionRole") | .Value' )
+        aws cloudformation create-change-set \
+        --stack-name ${{ inputs.stack_name }} \
+        --change-set-name ${{ inputs.stack_name }}-${{ inputs.change_set_version }}-current-tag \
+        --change-set-type UPDATE \
+        --template-body file://${{ inputs.template }} \
+        --capabilities ${{ inputs.capabilities }} \
+        --parameters ${{ steps.parse_parameters.outputs.PARAMETERS }} \
+        --tags Key="version",Value="${current_deployed_tag}" \
+        --role-arn="$ROLE"
+
+    - name: Header output
+      shell: bash
+      run: |
+        echo "## [${{ inputs.target_environment }}] Change Set for ${{ inputs.stack_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "- **Stack Name:** ${{ inputs.stack_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "- **Version Tag:** ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "The FULL change set below shows all changes including tag changes" >> $GITHUB_STEP_SUMMARY
+        echo "The change set with existing tag below shows all changes using the current tag and may be easier to identify changes" >> $GITHUB_STEP_SUMMARY
+        
+    - name: Describe Full Change Set
       shell: bash
       run: |
         STATUS="CREATE_IN_PROGRESS"
@@ -99,14 +129,17 @@ jobs:
         PARAMETERS=$(jq '.["Parameters"]' <<< "$CHANGE_SET")
         CAPABILITIES=$(jq '.["Capabilities"]' <<< "$CHANGE_SET")
         CHANGES=$(jq '.["Changes"]' <<< "$CHANGE_SET")
+        TAGS=$(jq '.["Tags"]' <<< "$CHANGE_SET")
+        TAGS="${TAGS//[$'\t\r\n ']}"
         if [ "$STATUS" == "FAILED" ] && [ "$STATUS_REASON" != "The submitted information didn't contain changes. Submit different information to create a change set." ]; then
           echo "Failed to create change set."
           exit 1
         fi
-        echo "## [${{ inputs.target_environment }}] Change Set for ${{ inputs.stack_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "<details><summary>[${{ inputs.target_environment }}] FULL Change Set for ${{ inputs.stack_name }}</summary>" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
         echo "- **Stack Name:** $STACK_NAME" >> $GITHUB_STEP_SUMMARY
         echo "- **Change Set Name:** $CHANGE_SET_NAME" >> $GITHUB_STEP_SUMMARY
-        echo "- **Version Tag:** ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
+        echo "- **Tags:** $TAGS"  >> $GITHUB_STEP_SUMMARY
         echo "- **Stack ID:** $STACK_ID" >> $GITHUB_STEP_SUMMARY
         echo "- **Change Set ID:** $CHANGE_SET_ID" >> $GITHUB_STEP_SUMMARY
         echo "" >> $GITHUB_STEP_SUMMARY
@@ -126,6 +159,64 @@ jobs:
           echo "$CHANGES" >> $GITHUB_STEP_SUMMARY
         fi
         echo "~~~"  >> $GITHUB_STEP_SUMMARY
+        echo "</details>" >> $GITHUB_STEP_SUMMARY
+
+    - name: Describe Change Set for existing tag
+      shell: bash
+      run: |
+        STATUS="CREATE_IN_PROGRESS"
+        while [ "$STATUS" == "CREATE_IN_PROGRESS" ]
+        do
+          echo "Getting change set..."
+          CHANGE_SET=$(aws cloudformation describe-change-set \
+          --stack-name ${{ inputs.stack_name }} \
+          --change-set-name ${{ inputs.stack_name }}-${{ inputs.change_set_version }}-current-tag)
+          STATUS=$(jq -r '.["Status"]' <<< "$CHANGE_SET")
+          if [ "$STATUS" == "CREATE_IN_PROGRESS" ]; then
+            echo "sleeping 1..."
+            sleep 1
+          fi
+        done
+        echo $CHANGE_SET
+        STACK_NAME=$(jq -r '.["StackName"]' <<< "$CHANGE_SET")
+        STACK_ID=$(jq -r '.["StackId"]' <<< "$CHANGE_SET")
+        CHANGE_SET_NAME=$(jq -r '.["ChangeSetName"]' <<< "$CHANGE_SET")
+        CHANGE_SET_ID=$(jq -r '.["ChangeSetId"]' <<< "$CHANGE_SET")
+        STATUS_REASON=$(jq -r '.["StatusReason"]' <<< "$CHANGE_SET")
+        PARAMETERS=$(jq '.["Parameters"]' <<< "$CHANGE_SET")
+        CAPABILITIES=$(jq '.["Capabilities"]' <<< "$CHANGE_SET")
+        CHANGES=$(jq '.["Changes"]' <<< "$CHANGE_SET")
+        TAGS="${TAGS//[$'\t\r\n ']}"
+        if [ "$STATUS" == "FAILED" ] && [ "$STATUS_REASON" != "The submitted information didn't contain changes. Submit different information to create a change set." ]; then
+          echo "Failed to create change set."
+          exit 1
+        fi
+        echo "<details><summary>[${{ inputs.target_environment }}] Change Set for ${{ inputs.stack_name }} with existing tag</summary>" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "## [${{ inputs.target_environment }}] Change Set for ${{ inputs.stack_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "- **Stack Name:** $STACK_NAME" >> $GITHUB_STEP_SUMMARY
+        echo "- **Change Set Name:** $CHANGE_SET_NAME" >> $GITHUB_STEP_SUMMARY
+        echo "- **Tags:** $TAGS"  >> $GITHUB_STEP_SUMMARY
+        echo "- **Stack ID:** $STACK_ID" >> $GITHUB_STEP_SUMMARY
+        echo "- **Change Set ID:** $CHANGE_SET_ID" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "#### Parameters:" >> $GITHUB_STEP_SUMMARY
+        echo "~~~ json"  >> $GITHUB_STEP_SUMMARY
+        echo "$PARAMETERS" >> $GITHUB_STEP_SUMMARY
+        echo "~~~"  >> $GITHUB_STEP_SUMMARY
+        echo "#### Capabilities:" >> $GITHUB_STEP_SUMMARY
+        echo "~~~ json"  >> $GITHUB_STEP_SUMMARY
+        echo "$CAPABILITIES" >> $GITHUB_STEP_SUMMARY
+        echo "~~~"  >> $GITHUB_STEP_SUMMARY
+        echo "#### Changes:" >> $GITHUB_STEP_SUMMARY
+        echo "~~~ json"  >> $GITHUB_STEP_SUMMARY
+        if [ "$STATUS" == "FAILED" ]; then
+          echo "$STATUS_REASON" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "$CHANGES" >> $GITHUB_STEP_SUMMARY
+        fi
+        echo "~~~"  >> $GITHUB_STEP_SUMMARY
+        echo "</details>" >> $GITHUB_STEP_SUMMARY
 
     - name: Delete Change Set
       if: ${{ inputs.execute_change_set == false }}
@@ -135,6 +226,12 @@ jobs:
         --stack-name ${{ inputs.stack_name }} \
         --change-set-name ${{ inputs.stack_name }}-${{ inputs.change_set_version }}
 
+    - name: Delete Change Set
+      shell: bash
+      run: |
+        aws cloudformation delete-change-set \
+        --stack-name ${{ inputs.stack_name }} \
+        --change-set-name ${{ inputs.stack_name }}-${{ inputs.change_set_version }}-current-tag
   
   execute_change_set:
     name: Execute Change Set
