AEA-3656 move splunk firehose to account resources (#51)
## Summary

**Remove items from this list if they are not relevant. Remove this line
once this has been done**

- Routine Change

### Details

- new lambda for processing cloudwatch logs to splunk format. Copied
from https://github.com/NHSDigital/prescriptionsforpatients
- SAM template to create AWS resources needed for
cloudwatch->firehose->splunk.
- new stack created as part of release pipeline called lambda-resources
that contains the above and can be used for other lambdas
- new stack called lambda-resources-pr-xxx created as part of pull
requests
- change to cloudformation github action to create an empty stack if it
does not exist
- add the tomorrow licence as we the lambda is based off
https://github.com/disney/terraform-aws-kinesis-firehose-splunk
- refactor pull request and release github action to use a new action
called release_all_stacks which releases all stacks
- new github actions to package and release SAM templates
- makefile targets for SAM related tasks
- extend parse_paramaters to use environment variables to pass in
dynamic secrets or variables which can then be passed to
cloudformation/SAM deployments
- changes for local environment to allow local node/SAM development
 
## Reviews Required

**Check who should review this. Remove this line once this has been
done**

- [x] Dev
- [ ] Test
- [ ] Tech Author
- [ ] Product Owner

## Review Checklist

:information_source: This section is to be filled in by the
**reviewer**.

- [ ] I have reviewed the changes in this PR and they fill all or part
of the acceptance criteria of the ticket, and the code is in a mergeable
state.
- [ ] I have reviewed any infrastructure changes listed in the workflow
summary.
- [ ] If there were infrastructure, operational, or build changes, I
have made sure there is sufficient evidence that the changes will work.
- [ ] I have ensured the jira ticket has been updated with the github
pull request link

---------

Co-authored-by: Adam Brown <adam.brown41@nhs.net>

diff --git a/.github/workflows/cloudformation.yml b/.github/workflows/cloudformation.yml
--- a/.github/workflows/cloudformation.yml
+++ b/.github/workflows/cloudformation.yml
@@ -24,8 +24,14 @@ on:
       change_set_version:
         required: true
         type: string
+      dynamic_vars:
+        required: false
+        type: string
+        default: "{}"
     secrets:
       cf_deploy_role:
+        required: false
+      parameter_secrets:
         required: false
       cf_create_changeset_role:
         required: true
@@ -45,19 +51,61 @@ jobs:
       with:
         ref: ${{ env.BRANCH_NAME }}
         fetch-depth: 0
-    
+
     - name: Assume create changeset role
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: eu-west-2
         role-to-assume: ${{ secrets.cf_create_changeset_role}}
         role-session-name: github-actions
-    
+
+    - name: check stack exists
+      id: check_stack_exists
+      shell: bash
+      run: |
+        stacks=$( aws cloudformation list-stacks --query "StackSummaries[].StackName" )
+        stack_exists=$( grep -c "${{ inputs.stack_name }}" <<< $stacks || true )
+        if [ "${stack_exists}" == "0" ]
+        then
+          echo "Stack does not exist"
+          echo "STACK_EXISTS=false" >> $GITHUB_OUTPUT
+        else
+          echo "Stack does exist"
+          echo "STACK_EXISTS=true" >> $GITHUB_OUTPUT
+        fi
+
+    - name: Assume create deploy stack role
+      if: ${{ steps.check_stack_exists.outputs.STACK_EXISTS == 'false' }} 
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-region: eu-west-2
+        role-to-assume: ${{ secrets.cf_deploy_role}}
+        role-session-name: github-actions
+
+    - name: create stack
+      if: ${{ steps.check_stack_exists.outputs.STACK_EXISTS == 'false' }} 
+      shell: bash
+      run: |
+        aws cloudformation create-stack --stack-name ${{ inputs.stack_name }} \
+        --template-body file://./cloudformation/empty_stack.yml
+
+    - name: Assume create changeset role
+      if: ${{ steps.check_stack_exists.outputs.STACK_EXISTS == 'false' }} 
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-region: eu-west-2
+        role-to-assume: ${{ secrets.cf_create_changeset_role}}
+        role-session-name: github-actions
+        
     - name: Parse Parameters
+      env:
+        parameter_secrets: ${{ secrets.parameter_secrets }}
+        dynamic_vars: ${{ inputs.dynamic_vars }}
       id: parse_parameters
       shell: bash
       run: |
-        echo PARAMETERS=$(python scripts/parse_parameters.py ${{ inputs.target_environment }} ${{ inputs.stack_name }}) >> $GITHUB_OUTPUT
+        PARAMETERS=$(python scripts/parse_parameters.py ${{ inputs.target_environment }} ${{ inputs.stack_name }} )
+        echo "PARAMETERS=${PARAMETERS}" >> $GITHUB_OUTPUT
 
     - name: Create Change Set with new tags
       shell: bash
@@ -218,7 +266,7 @@ jobs:
         echo "~~~"  >> $GITHUB_STEP_SUMMARY
         echo "</details>" >> $GITHUB_STEP_SUMMARY
 
-    - name: Delete Change Set
+    - name: Delete Change Set for new tag
       if: ${{ inputs.execute_change_set == false }}
       shell: bash
       run: |
@@ -226,7 +274,7 @@ jobs:
         --stack-name ${{ inputs.stack_name }} \
         --change-set-name ${{ inputs.stack_name }}-${{ inputs.change_set_version }}
 
-    - name: Delete Change Set
+    - name: Delete Change Set for existing tag
       shell: bash
       run: |
         aws cloudformation delete-change-set \
@@ -287,5 +335,10 @@ jobs:
             echo "Failed to execute change set, rollback failed."
             echo "$STACKS"
             exit 1
+          elif [ "$STATUS" == "UPDATE_COMPLETE" ]; then
+            echo "Execute change set comeplete."
+            exit 0
           fi
-          echo "Execute change set comeplete."
+          echo "Failed to execute change set, for unknown reason."
+          echo "$STACKS"
+          exit 1
